### ISSUE TITLE
TypeStrong.org parked

### ISSUE THREAD

**Issue by goatandsheep** [TypeStrong/typestrong.github.io#2]
Despite the link to typestrong.org on the organization page, the website is down and displaying a parking page.

**Comment by nycdotnet** [comment]
Who owns this?

**Comment by blakeembrey** [comment]
@basarat

**Comment by basarat** [comment]
Discussing with blake in email :rose:

**Comment by mtgto** [comment]
Hey, what has become of this issue?
It seems to be still parked typestrong.org && link of organization page is not changed.

**Comment by blakeembrey** [comment]
Closing as the domain is currently maintained.
